#!/usr/bin/env python3
"""mkprofile — build a profile bound to one route, plus the locks that hold it.

There are three ways to lock, and which of them actually works is one of the
questions this stage exists to answer, so all three are generated.

  user.js       inside the profile. A user can delete it. Not a lock — a default.
  policies.json distribution/ in the install directory. The enterprise path.
  autoconfig    mozilla.cfg + defaults/pref/local-settings.js. lockPref lives here.

A fourth exists: passing `locked` as the third argument in the built-in pref
files. That is how the base locks privacy.resistFingerprinting itself. It is the
simplest option for a fork, but it needs a rebuild, so it cannot be made here.
"""
import argparse, json, os, shutil, sys

# This table is the only thing that varies by route. Every other pref must be
# identical across profiles, because a pref that differs is a fingerprint that differs.
# `kind` is the proxy type. I2P uses HTTP (4444), not SOCKS (4447): the I2P
# project recommends it, and it keeps name resolution inside the router.
TRANSPORTS = {
    "direct":  {"proxy": None,                 "kind": None,   "suffix": None,     "webrtc": True},
    "fake":    {"proxy": ("127.0.0.1", 19999), "kind": "socks", "suffix": None,     "webrtc": False},
    "tor":     {"proxy": ("127.0.0.1", 9150),  "kind": "socks", "suffix": ".onion", "webrtc": False},
    "i2p":     {"proxy": ("127.0.0.1", 4444),  "kind": "http",  "suffix": ".i2p",   "webrtc": False},
}

def prefs_for(t, dns_mode):
    c = TRANSPORTS[t]
    p = {}
    if c["proxy"]:
        host, port = c["proxy"]
        # Firefox's DNS guard only exists at type=1 (manual). PAC (type=2) and
        # extension-based proxying do not pass through it, so both are forbidden.
        p["network.proxy.type"] = 1
        if c["kind"] == "socks":
            p.update({
                "network.proxy.socks": host,
                "network.proxy.socks_port": port,
                "network.proxy.socks_version": 5,
                # Split in Firefox 128: socks_remote_dns is now SOCKS4 only, and
                # socks5_remote_dns is what actually governs SOCKS5. Measured:
                # with socks5_remote_dns=false, 6 DNS packets escaped.
                "network.proxy.socks5_remote_dns": True,
                "network.proxy.socks_remote_dns": True,
            })
        else:
            p.update({
                "network.proxy.http": host, "network.proxy.http_port": port,
                "network.proxy.ssl": host,  "network.proxy.ssl_port": port,
            })
        p.update({
                # The name reads backwards. It must be true for connections to
                # localhost to go through the proxy; false makes localhost an
                # exception that goes out directly. Measured; Tor Browser sets true too.
            "network.proxy.allow_hijacking_localhost": True,
            "network.proxy.failover_direct": False,
            "network.proxy.allow_bypass": False,
            "network.proxy.no_proxies_on": "",
        })
    else:
        p["network.proxy.type"] = 0

    if not c["webrtc"]:
        p["media.peerconnection.enabled"] = False

    # Three DNS arrangements, so it can be measured which one actually holds.
    if dns_mode == "off":
        # Disable the DNS subsystem itself. The question is whether an extension's
        # browser.dns.resolve is blocked along with it.
        p["network.dns.disabled"] = True
        p["network.trr.mode"] = 5
    elif dns_mode == "trr-off":
        p["network.trr.mode"] = 5          # DoH off
    elif dns_mode == "trr-only":
        p["network.trr.mode"] = 3          # DoH only; does it go through the proxy?

    # Silence background traffic that would be noise in a measurement.
    # Prototype only; the product decides these on their own merits.
    p.update({
        "app.update.auto": False,
        "app.update.enabled": False,
        "extensions.update.enabled": False,
        "extensions.update.autoUpdateDefault": False,
        "extensions.blocklist.enabled": False,
        "browser.search.update": False,
        "datareporting.healthreport.uploadEnabled": False,
        "toolkit.telemetry.enabled": False,
        "network.captive-portal-service.enabled": False,
        "network.connectivity-service.enabled": False,
        "browser.startup.homepage": "about:blank",
        "browser.newtabpage.enabled": False,
        "browser.shell.checkDefaultBrowser": False,
        "browser.aboutwelcome.enabled": False,
        "security.OCSP.enabled": 0,
        # Opens connections before the first request, possibly ahead of the
        # proxy decision. Off.
        "network.dns.disablePrefetch": True,
        "network.prefetch-next": False,
        "network.predictor.enabled": False,
        "browser.urlbar.speculativeConnect.enabled": False,
    })
    return p

def write_userjs(path, prefs):
    with open(path, "w") as f:
        f.write("// generated by mkprofile. A default, not a lock.\n")
        for k, v in prefs.items():
            f.write('user_pref("%s", %s);\n' % (k, json.dumps(v)))

def write_autoconfig(install_dir, prefs, lock=True):
    cfg = os.path.join(install_dir, "mullvad-browser.cfg")
    with open(cfg, "w") as f:
        f.write("// the first line is discarded; it must be a comment.\n")
        for k, v in prefs.items():
            f.write('%s("%s", %s);\n' % ("lockPref" if lock else "defaultPref", k, json.dumps(v)))
    d = os.path.join(install_dir, "defaults", "pref")
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, "local-settings.js"), "w") as f:
        f.write('pref("general.config.filename", "mullvad-browser.cfg");\n')
        f.write('pref("general.config.obscure_value", 0);\n')
        f.write('pref("general.config.sandbox_enabled", false);\n')
    return cfg

def write_policies(install_dir, prefs):
    d = os.path.join(install_dir, "distribution")
    os.makedirs(d, exist_ok=True)
    pol = {"policies": {"Preferences": {}}}
    for k, v in prefs.items():
        pol["policies"]["Preferences"][k] = {"Value": v, "Status": "locked"}
    path = os.path.join(d, "policies.json")
    with open(path, "w") as f:
        json.dump(pol, f, indent=2)
    return path

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--transport", required=True, choices=sorted(TRANSPORTS))
    ap.add_argument("--profile", required=True, help="profile directory")
    ap.add_argument("--install", help="install directory (for policies/autoconfig)")
    ap.add_argument("--lock", choices=["userjs", "policies", "autoconfig", "all"], default="userjs")
    ap.add_argument("--dns", choices=["default", "off", "trr-off", "trr-only"], default="trr-off")
    ap.add_argument("--socks-port", type=int, help="override the route's default port")
    ap.add_argument("--fresh", action="store_true", help="wipe and recreate the profile")
    a = ap.parse_args()

    if a.socks_port:
        c = TRANSPORTS[a.transport]
        if c["proxy"]:
            TRANSPORTS[a.transport] = dict(c, proxy=(c["proxy"][0], a.socks_port))

    prefs = prefs_for(a.transport, a.dns)

    if a.fresh and os.path.isdir(a.profile):
        shutil.rmtree(a.profile)
    os.makedirs(a.profile, exist_ok=True)

    made = []
    if a.lock in ("userjs", "all"):
        write_userjs(os.path.join(a.profile, "user.js"), prefs)
        made.append("user.js")
    if a.lock in ("policies", "all"):
        if not a.install:
            sys.exit("--install is required")
        made.append(write_policies(a.install, prefs))
    if a.lock in ("autoconfig", "all"):
        if not a.install:
            sys.exit("--install is required")
        made.append(write_autoconfig(a.install, prefs))

    print("route=%s  profile=%s  dns=%s" % (a.transport, a.profile, a.dns))
    print("%d prefs · wrote: %s" % (len(prefs), ", ".join(made)))

main()
