#!/usr/bin/env python3
"""Rewrite Firefox's primitive colour tokens onto the BBIWY ink ramp.

The browser chrome reads its colours through ~5200 var() references that all
bottom out in about 130 primitive tokens declared in the design system's
tokens-shared.css. Redefining those primitives is therefore the whole of the
monochrome restyle: everything downstream follows.

Each primitive is replaced by the grey of the same WCAG relative luminance,
read off the ink ramp. Matching luminance rather than picking greys by eye
keeps every contrast ratio Mozilla tuned, so nothing silently drops below the
threshold it was designed to meet.

Status stays coloured. The status hues are greyed at the primitive level, so
red used as decoration goes grey, and then the semantic status tokens are put
back in colour explicitly. Colour therefore means "something happened", never
"this is the red button".

Usage:
    graytokens.py <tokens-shared.css> > bbiwy-tokens.css
"""

import re
import sys

# docs/DESIGN-LANGUAGE.ko.md section 1. Neither end is pure: white text on pure
# black haloes, and it is tiring to read for long stretches.
INK = [
    "#08090A", "#101214", "#191C1F", "#24282C", "#3A3F45",
    "#6E757D", "#A8AFB6", "#E4E7EA", "#F7F9FA",
]

# The only three colours the product may show, and only to report a state.
SIGNAL = {"ok": "#7CE3B1", "warn": "#F0C674", "fail": "#FF5C5C"}

PRIMITIVE = re.compile(r"^\s*(--color-[a-z0-9-]+)\s*:\s*(#[0-9a-fA-F]{3,8})\s*;")


def parse_hex(value):
    h = value.lstrip("#")
    if len(h) == 3:
        h = "".join(c * 2 for c in h)
    if len(h) == 8:          # #rrggbbaa
        h = h[:6]
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def luminance(rgb):
    """WCAG 2.x relative luminance."""
    def channel(v):
        v /= 255
        return v / 12.92 if v <= 0.04045 else ((v + 0.055) / 1.055) ** 2.4
    r, g, b = (channel(c) for c in rgb)
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def ink_ramp():
    """The ink stops paired with their luminance, darkest first."""
    return [(luminance(parse_hex(stop)), parse_hex(stop)) for stop in INK]


def gray_for(rgb, ramp):
    """The point on the ink ramp whose luminance matches this colour."""
    target = luminance(rgb)
    if target <= ramp[0][0]:
        return ramp[0][1]
    if target >= ramp[-1][0]:
        return ramp[-1][1]
    for (lo_lum, lo), (hi_lum, hi) in zip(ramp, ramp[1:]):
        if lo_lum <= target <= hi_lum:
            span = hi_lum - lo_lum
            t = 0.0 if span == 0 else (target - lo_lum) / span
            return tuple(round(a + (b - a) * t) for a, b in zip(lo, hi))
    return ramp[-1][1]


def to_hex(rgb):
    return "#{:02x}{:02x}{:02x}".format(*rgb)


def contrast(a, b):
    la, lb = luminance(a), luminance(b)
    lo, hi = sorted((la, lb))
    return (hi + 0.05) / (lo + 0.05)


def read_primitives(path):
    with open(path, encoding="utf-8") as handle:
        for line in handle:
            match = PRIMITIVE.match(line)
            if match:
                yield match.group(1), match.group(2)


def main(argv):
    if len(argv) != 2:
        sys.stderr.write(__doc__)
        return 2

    ramp = ink_ramp()
    seen = set()
    rows = []
    for name, value in read_primitives(argv[1]):
        # A primitive can be declared more than once: the base layer, then
        # again under prefers-contrast and forced-colors. One override at the
        # top of the cascade covers every one of them.
        if name in seen:
            continue
        seen.add(name)
        rows.append((name, value, to_hex(gray_for(parse_hex(value), ramp))))

    out = sys.stdout.write
    out("/* Generated by tools/theme/graytokens.py -- do not edit by hand.\n")
    out(" *\n")
    out(" * Declared outside every @layer, so it outranks the whole design\n")
    out(" * system: unlayered rules beat layered ones no matter their order.\n")
    out(" */\n\n")
    out(":root,\n:host(.anonymous-content-host) {\n")
    for name, was, now in rows:
        out(f"  {name}: {now};  /* was {was} */\n")
    out("}\n\n")

    out("/* Status is the one thing that may still carry colour. The hues above\n")
    out(" * are grey now, so these have to be stated outright. */\n")
    out(":root,\n:host(.anonymous-content-host) {\n")
    for role, token in (("fail", "critical"), ("ok", "success"), ("warn", "warning")):
        out(f"  --icon-color-{token}: {SIGNAL[role]};\n")
        out(f"  --text-color-{token}: {SIGNAL[role]};\n")
        out(f"  --border-color-{token}: {SIGNAL[role]};\n")
    out("}\n")

    sys.stderr.write(f"{len(rows)} primitives rewritten\n")

    # The ramp is only worth anything if body text still clears WCAG AA.
    ink = [parse_hex(stop) for stop in INK]
    for label, fg, bg in (
        ("body text on window", ink[7], ink[0]),
        ("headings on window", ink[8], ink[0]),
        ("secondary text on toolbar", ink[6], ink[1]),
    ):
        ratio = contrast(fg, bg)
        mark = "ok " if ratio >= 4.5 else "LOW"
        sys.stderr.write(f"  {mark} {label}: {ratio:.2f}:1\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
